[package]
name = "tsv"
version = "0.2.0"
authors = ["aleskei <aleksei.pronkin@skoltech.ru>"]
edition = "2018"

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
clap = {version  = "2.31.0", features = ["yaml"]}